### ISSUE TITLE
Should we make the validator instance thread-safe?

### ISSUE THREAD

**Issue by ewoutkramer** [FirelyTeam/firely-validator-api#381]
This discussion https://chat.fhir.org/#narrow/stream/179171-dotnet/topic/Encountered.20an.20error.20while.20loading.20schema surfaces the issue that most of our code is not thread safe. It does not have to be, and in fact most classes in Microsoft's stack aren't either, but in this case it does mean that to safely do multi-threaded validation, one needs to create multiple instances of the validator and the resolvers, which will mean multiple instances of caches.

This is an inconvenience that we might want to fix in a future (major?) release of the validator.

**Comment by darena-antonw** [comment]
we've ran in to issues with thread safety, repro here: https://github.com/darena-antonw/firely-validator-thread-safety-repro

```
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at Firely.Fhir.Validation.Compilation.StructureDefinitionCorrectionsResolver.<correctStructureDefinition>g__correctConstraints|8_2(IElementList elements)
   at Firely.Fhir.Validation.Compilation.StructureDefinitionCorrectionsResolver.correctStructureDefinition(Resource result)
   at Firely.Fhir.Validation.Compilation.StructureDefinitionCorrectionsResolver.ResolveByCanonicalUriAsync(String uri)
   at Hl7.Fhir.Specification.Source.IAsyncResourceResolver.TryResolveByCanonicalUriAsync(String uri)
   at Hl7.Fhir.Specification.Source.ResourceResolverExtensions.FindStructureDefinitionAsync(IAsyncResourceResolver resolver, String uri)
   at Firely.Fhir.Validation.Compilation.StructureDefinitionToElementSchemaResolver.GetSchema(Canonical schemaUri)
```

having a _warm up_ run before doing the actual work helps to resolve this issue (in most cases)

I think it's definitely worth outlining that the Validator is not thread safe somewhere in the README or the docs.
